# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:10.15.3

pipelines:
  default:
    - step:
        caches:
          - node
        deployment: production
        script: # Modify the commands below to build your repository.
          - npm install
          - pipe: atlassian/google-app-engine-deploy:0.6.0
            variables:
              KEY_FILE: $KEY_FILE
              PROJECT: 'heroic-calculus-263602'
              # DEPLOYABLES: '<string>' # Optional
              # VERSION: '<string>' # Optional.
              # BUCKET: '<string>' # Optional.
              # IMAGE: '<string>' # Optional.
              # PROMOTE: '<boolean>' # Optional
              # STOP_PREVIOUS_VERSION: '<boolean>' # Optional.
              # EXTRA_ARGS: '<string>' # Optional.
              # DEBUG: '<boolean>' # Optional.
              # CLOUD_BUILD_TIMEOUT: '<integer>' # Optional

