export const CREATE_REQUEST = 'CREATE_REQUEST';
export const REQUEST_SUCCESS = 'REQUEST_SUCCESS';
export const REQUEST_FAILURE = 'REQUEST_FAILURE';
export const LOGIN_REQUEST= 'LOGIN_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';
export const REGISTER_REQUEST= 'REGISTER_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const SIGNUP_USER = 'SIGNUP_USER';
export const SIGNUP_ERROR_USER = 'SIGNUP_ERROR_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGOUT_ERROR = 'LOGOUT_ERROR';

export const VERIFYEMAIL_SUCCESS = 'VERIFYEMAIL_SUCCESS';
export const VERIFYEMAIL_ERROR = 'VERIFYEMAIL_ERROR';

export const IS_EMAIL_VERIFY_SUCCESS = 'IS_EMAIL_VERIFY_SUCCESS';
export const IS_EMAIL_VERIFY_ERROR = 'IS_EMAIL_VERIFY_ERROR';

export const RESET_PASSWORD_SUCCESS='RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_ERROR='RESET_PASSWORD_ERROR';

export const CHANGE_PASSWORD_SUCCESS='CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_ERROR='CHANGE_PASSWORD_ERROR';

/* events for profile editing*/
export const GET_PROFILE_SUCCESS="GET_PROFILE_SUCCESS";
export const GET_PROFILE_ERROR="GET_PROFILE_ERROR";

export const PROFILE_EDIT_SUCCESS="PROFILE_EDIT_SECCESS";
export const PROFILE_EDIT_ERROR="PROFILE_EDIT_ERROR";
/*events for profile language editing*/
export const PROFILE_LANGUAGE_ADD_SUCCESS="PROFILE_LANGUAGE_ADD_SECCESS";
export const PROFILE_LANGUAGE_ADD_ERROR="PROFILE_LANGUAGE_ADD_ERROR";
export const PROFILE_LANGUAGE_EDIT_SUCCESS="PROFILE_LANGUAGE_EDIT_SECCESS";
export const PROFILE_LANGUAGE_EDIT_ERROR="PROFILE_LANGUAGE_EDIT_ERROR";
export const PROFILE_LANGUAGE_DELETE_SUCCESS="PROFILE_LANGUAGE_DELETE_SECCESS";
export const PROFILE_LANGUAGE_DELETE_ERROR="PROFILE_LANGUAGE_DELETE_ERROR";

/*events for experience editing*/
export const EXPERIENCE_ADD_SUCCESS="EXPERIENCE_ADD_SUCCESS";
export const EXPERIENCE_ADD_ERROR="EXPERIENCE_ADD_ERROR";
export const EXPERIENCE_EDIT_SUCCESS="EXPERIENCE_EDIT_SUCCESS";
export const EXPERIENCE_EDIT_ERROR="EXPERIENCE_EDIT_ERROR";
export const EXPERIENCE_REMOVE_SUCCESS="EXPERIENCE_REMOVE_SUCCESS";
export const EXPERIENCE_REMOVE_ERROR="EXPERIENCE_REMOVE_ERROR";
/*events for experience editing*/
export const EDUCATION_ADD_SUCCESS="EDUCATION_ADD_SUCCESS";
export const EDUCATION_ADD_ERROR="EDUCATION_ADD_ERROR";
export const EDUCATION_EDIT_SUCCESS="EDUCATION_EDIT_SUCCESS";
export const EDUCATION_EDIT_ERROR="EDUCATION_EDIT_ERROR";
export const EDUCATION_REMOVE_SUCCESS="EDUCATION_REMOVE_SUCCESS";
export const EDUCATION_REMOVE_ERROR="EDUCATION_REMOVE_ERROR";

export const CHANGE_PICTURE_SUCCESS="CHANGE_PICTURE_SUCCESS";
export const CHANGE_PICTURE_ERROR="CHANGE_PICTURE_ERROR";
export const ADMIN_USER_LIST_SUCCESS="ADMIN_USER_LIST_SUCCESS";
export const ADMIN_USER_LIST_ERROR="ADMIN_USER_LIST_ERROR";
export const USER_REMOVE_SUCCESS="USER_REMOVE_SUCCESS";
export const USER_REMOVE_ERROR="USER_REMOVE_ERROR";

export const CONTACTUS_ADD_SUCCESS="CONTACTUS_ADD_SUCCESS";
export const CONTACTUS_ADD_ERROR="CONTACTUS_ADD_ERROR";

export const CODE_ADD_SUCCESS="CODE_ADD_SUCCESS";
export const CODE_ADD_ERROR="CODE_ADD_ERROR";
export const CODE_EDIT_SUCCESS="CODE_EDIT_SUCCESS";
export const CODE_EDIT_ERROR="CODE_EDIT_ERROR";
export const CODE_REMOVE_SUCCESS="CODE_REMOVE_SUCCESS";
export const CODE_REMOVE_ERROR="CODE_REMOVE_ERROR";
export const GET_CODE_SUCCESS="GET_PROFILE_SUCCESS";
export const GET_CODE_ERROR="GET_PROFILE_ERROR";

/*events for media editing*/
export const MEDIA_ADD_SUCCESS="MEDIA_ADD_SUCCESS";
export const MEDIA_ADD_ERROR="MEDIA_ADD_ERROR";
export const MEDIA_EDIT_SUCCESS="MEDIA_EDIT_SUCCESS";
export const MEDIA_EDIT_ERROR="MEDIA_EDIT_ERROR";
export const MEDIA_REMOVE_SUCCESS="MEDIA_REMOVE_SUCCESS";
export const MEDIA_REMOVE_ERROR="MEDIA_REMOVE_ERROR";

/*events for visual portollo editing*/
export const PORTFOLLO_ADD_SUCCESS="PORTFOLLO_ADD_SUCCESS";
export const PORTFOLLO_ADD_ERROR="PORTFOLLO_ADD_ERROR";
export const PORTFOLLO_EDIT_SUCCESS="PORTFOLLO_EDIT_SUCCESS";
export const PORTFOLLO_EDIT_ERROR="PORTFOLLO_EDIT_ERROR";
export const PORTFOLLO_REMOVE_SUCCESS="PORTFOLLO_REMOVE_SUCCESS";
export const PORTFOLLO_REMOVE_ERROR="PORTFOLLO_REMOVE_ERROR";

/*events for media editing*/
export const SPECIALTIES_ADD_SUCCESS="SPECIALTIES_ADD_SUCCESS";
export const SPECIALTIES_ADD_ERROR="SPECIALTIES_ADD_ERROR";
export const SPECIALTIES_EDIT_SUCCESS="SPECIALTIES_EDIT_SUCCESS";
export const SPECIALTIES_EDIT_ERROR="SPECIALTIES_EDIT_ERROR";
export const SPECIALTIES_REMOVE_SUCCESS="SPECIALTIES_REMOVE_SUCCESS";
export const SPECIALTIES_REMOVE_ERROR="SPECIALTIES_REMOVE_ERROR";

/*events for progress editing*/
export const PROGRESS_ADD_SUCCESS="PROGRESS_ADD_SUCCESS";
export const PROGRESS_ADD_ERROR="PROGRESS_ADD_ERROR";
export const PROGRESS_EDIT_SUCCESS="PROGRESS_EDIT_SUCCESS";
export const PROGRESS_EDIT_ERROR="PROGRESS_EDIT_ERROR";
export const PROGRESS_REMOVE_SUCCESS="PROGRESS_REMOVE_SUCCESS";
export const PROGRESS_REMOVE_ERROR="PROGRESS_REMOVE_ERROR";

/*events for about editing*/
export const ABOUT_ADD_SUCCESS="ABOUT_ADD_SUCCESS";
export const ABOUT_ADD_ERROR="ABOUT_ADD_ERROR";
export const ABOUT_EDIT_SUCCESS="ABOUT_EDIT_SUCCESS";
export const ABOUT_EDIT_ERROR="ABOUT_EDIT_ERROR";
export const ABOUT_REMOVE_SUCCESS="ABOUT_REMOVE_SUCCESS";
export const ABOUT_REMOVE_ERROR="ABOUT_REMOVE_ERROR";

export const IS_EMAIL_RESEND_SUCCESS = 'IS_EMAIL_RESEND_SUCCESS';
export const IS_EMAIL_RESEND_ERROR = 'IS_EMAIL_RESEND_ERROR';


export const BLOG_ADD_SUCCESS = "BLOG_ADD_SUCCESS";
export const BLOG_ADD_ERROR = "BLOG_ADD_ERROR";
export const BLOG_EDIT_SUCCESS = "BLOG_EDIT_SUCCESS";
export const BLOG_EDIT_ERROR = "BLOG_EDIT_ERROR";
export const BLOG_REMOVE_SUCCESS = "BLOG_REMOVE_SUCCESS";
export const BLOG_REMOVE_ERROR = "BLOG_REMOVE_ERROR";